### ISSUE TITLE
Maybe unsound in new_raw_clone

### ISSUE THREAD

**Issue by lwz23** [nixops4/nixops4#65]
Hello, thank you for your contribution in this project, I am scanning the unsoundness problem in rust project.
I notice the following code:
```
pub struct StorePath {
    raw: *mut raw::StorePath,
}
impl StorePath {
    /// This is a low level function that you shouldn't have to call unless you are developing the Nix bindings.
    ///
    /// Construct a new `StorePath` by first cloning the C store path.
    /// This does not take ownership of the C store path, so it should be a borrowed value, or you should free it.
    pub fn new_raw_clone(raw: *const raw::StorePath) -> Self {
        Self::new_raw(unsafe { raw::store_path_clone(raw as *mut raw::StorePath) })
    }
    /// This is a low level function that you shouldn't have to call unless you are developing the Nix bindings.
    ///
    /// Takes ownership of a C `nix_store_path`. It will be freed when the `StorePath` is dropped.
    pub fn new_raw(raw: *mut raw::StorePath) -> Self {
        StorePath { raw }
    }
    pub fn name(&self) -> Result<String> {
        unsafe {
            let mut r = result_string_init!();
            raw::store_path_name(
                self.raw,
                Some(callback_get_result_string),
                callback_get_result_string_data(&mut r),
            );
            r
        }
    }
}
```
Considering that `pub mod path`, and `new`  is also a pub function. I assume that users can directly call this function. This potential situation could result in `raw::store_path_clone` operating on a null pointer, I am not sure what will raw::store_path_clone do on a null pointer but I guess it might trigger undefined behavior (UB). More importantly, I'm not sure that structs built this way will not UB when other methods are called, eg. name. For safety reasons, I felt it necessary to report this issue. If you have performed checks elsewhere that ensure this is safe, please don’t take offense at my raising this issue.
I suggest Several possible fixes: 
1. If there is no external usage for `StorePath` or `new_raw_clone`, they should not marked as `pub`, at least its `new_raw_clone` should not marked as `pub` 
2. `new_raw_clone` method should add additional check for null pointer.
3. mark new_raw_clone method as unsafe and proper doc to let users know that they should provide valid Pointers.

**Comment by lwz23** [comment]
same for https://github.com/nixops4/nixops4/blob/b9dc536b7a0ea6dd947949c59c545e7fa604351a/rust/nix-store/src/path.rs#L22

**Comment by lwz23** [comment]
ping

**Comment by roberth** [comment]
Hi @lwz23, thank you for finding this potential problem.
I've opened #68 to address it. Could you have a look?

**Comment by lwz23** [comment]
Ok, thanks for your reply! I will have a look.
